### ISSUE TITLE
unused argument (na.rm = TRUE) error occur when I use compartment_matrixplot function

### ISSUE THREAD

**Issue by hanshanmengqi** [robinweide/GENOVA#328]
Hi,

Thank you for your powerful tool. Now I met a problem that is `unused argument (na.rm = TRUE)` when I use **compartment_matrixplot** 

The screenshot is shown below:
![screenshot](https://github.com/robinweide/GENOVA/assets/93769611/67264b69-ec27-46ae-aaa0-45ee3359b624)

However, it's normal when I just have one sample. Please take a look at screenshot 2

![screenshot2](https://github.com/robinweide/GENOVA/assets/93769611/db2f1d7e-de36-4712-8b35-5cd8dda03870)

Could you please help me?

Thank you for your time.
Han

**Comment by ZHONGHONGXIN** [comment]
l meet the same error.

**Comment by amodrek** [comment]
> CS_out
A GENOVA 'CS_discovery' object involving the following 2 experiment(s):
'parental', 'c142_3hr' at a resolution of 250 kb.

Contains the following slots:
 - compart_scores:      A 12091 x 6 data.frame containing signed compartment scores.

0 centromeres spanning a total of 0 bins have been ignored.
> any(is.na(CS_out))
[1] FALSE
> any(is.na(CS_out$compart_scores))
[1] TRUE
> head(CS_out$compart_scores)
  chrom   start     end bin   parental   c142_3hr
1     M       0  250000   1         NA         NA
2     1       0  250000   2 -0.7955663 -0.8143696
3     1  250000  500000   3 -0.8040515 -0.8178153
4     1  500000  750000   4 -0.7916306 -0.7965462
5     1  750000 1000000   5 -0.3235744 -0.2550182
6     1 1000000 1250000   6 -0.2391273 -0.1980523
> CS_out$compart_scores <- na.omit(CS_out$compart_scores)
> any(is.na(CS_out))
[1] FALSE
> compartment_matrixplot(
+     exp1 = parental_mat,
+     exp2= cuts142_3hr_mat,
+     CS_discovery= CS_out,
+     metric = "obsexp",
+     chrom = "1", arm="all"
+     )
Error in rev(range(compbreaks), na.rm = TRUE) : 
  unused argument (na.rm = TRUE)

**Comment by amodrek** [comment]
same error!

**Comment by teunbrand** [comment]
Thanks for the report everyone, I think it should be fixed in the dev version now

**Comment by davidecarnevali** [comment]
Same error with the latest version
Any hint?
Thank you

D.

**Comment by davidecarnevali** [comment]
> Thanks for the report everyone, I think it should be fixed in the dev version now

The lates version (1.0.1) still have the problem.
By checking the source code of the 'compartmen_matrixplot' function in master and dev I see a difference (line 182)
The devolpment version is:
`xlim = rev(range(compbreaks, na.rm = TRUE)), ylim = loclim`

while the code in the master branch is:
`xlim = rev(range(compbreaks), na.rm = TRUE), ylim = loclim`

@teunbrand can you fix it?

Thanx

D.

**Comment by teunbrand** [comment]
The dev version doesn't work for your case?

**Comment by davidecarnevali** [comment]
Yes, just installed and worked but only tried it for
compartment_matrixplot, no the whole pipeline
Thank you

**Comment by deWitLab** [comment]
> The dev version doesn't work for your case?

There is a problem with the `na.rm = TRUE`, this is an argument for `rev` and should be a argument for `range`, this is why it crashes when you want to plot two Hi-C maps. Can this be fixed?

**Comment by teunbrand** [comment]
> Can this be fixed?

This should be fixed in the development version

**Comment by wwowo** [comment]
It seems this error was not fixed in version 1.0.1. I resolved the issue after modifying the source code.
`trace(GENOVA::compartment_matrixplot, edit = TRUE)`

<img width="667" height="146" alt="Image" src="https://github.com/user-attachments/assets/a6c371ef-efe0-4641-9024-936cd3e18d83" />
