### ISSUE TITLE
Matrix plot visualization issue

### ISSUE THREAD

**Issue by LucasMcNU** [robinweide/GENOVA#347]
When using GENOVA with R  3.0 (or 2.3) on the HPC at my uni, I recently came upon an issue when trying to use any of the visualization functions (Pyramid(), Matrixplot(), etc..)

```
Error in guides$setup(scales, aesthetics, default = params$guide_default %||%  : 
  attempt to apply non-function
```

I uninstalled and reinstalled GENOVA. The issue persisted. Here is an example call:

```
GENOVA::pyramid(exp = wt.100kb, 
        chrom = "8",
        start = 132787754,
        end=133587757)
```

The visualization functions worked fine with this same data a week ago and ```visualize() ``` still  works fine with relative contact probability or aggregate tad analysis. It appears to just be an issue with generating matrix plots

**Comment by teunbrand** [comment]
I can only reproduce the `pyramid()` issue, the others seem to work as intended. In any case, this is due to an update in ggplot2 3.5.0, which we'll have to accommodate in GENOVA.

``` r
library(GENOVA)

exp <- get_test_data("150k", download = TRUE)

pyramid(exp, "chr22", 30e6, 35e6)
#> Error in guides$setup(scales, aesthetics, default = params$guide_default %||% : attempt to apply non-function
```

```r
hic_matrixplot(exp, chrom = "chr22", start = 30e6, end = 35e6)
#> No colour limits were given: using 99% percentile: 11581.
```

![](https://i.imgur.com/L7QYYO3.png)

``` r
trans_matrixplot(exp, chrom_up = "chr22", chrom_down = "chr22",
                 start_up = 30e6, start_down = 30e6,
                 end_up = 35e6, end_down = 35e6)
```

![](https://i.imgur.com/bwzFUvK.png)

``` r
insulation_matrixplot(exp, chrom = "chr22", start = 30e6, end = 35e6)
#> Limits set to [0,7188]
```

![](https://i.imgur.com/dUsvN2M.png)

``` r
compartment_matrixplot(exp, chrom = "chr22", arm = "q")
#> Limits set to [0,4543]
```

![](https://i.imgur.com/Mbm5Yj8.png)

<sup>Created on 2024-03-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by LucasMcNU** [comment]
I'll try the other plotting functions in the meantime. Thank you for the quick response!

**Comment by teunbrand** [comment]
The `pyramid()` function should be fixed now. If other functions are unaffected, please feel free to close the issue.

**Comment by LucasMcNU** [comment]
Hmm.. I'm still having this issue, only with pyramid(), even after updating Genova. Any idea why?

**Comment by knight-hzj** [comment]
> The `pyramid()` function should be fixed now. If other functions are unaffected, please feel free to close the issue.

Hi, Could you please let me know How go fix this issue, I also got the same error like: Error in guides$setup(scales, aesthetics, default = params$guide_default %||% : attempt to apply non-function.  Thank you!!!
